### ISSUE TITLE
Allow specifying LFN in f-stream without enabling `user` parameter

### ISSUE THREAD

**Issue by sognetic** [maxfischer2781/xrootdlib#1]
As described by https://xrootd.slac.stanford.edu/doc/dev51/xrd_monitoring.htm#_Toc49119288, the `dictid` parameter in the FileOpen structure is always 0 if no user information is requested in the XRootD configuration. This is currently not covered by `xrootdlib`.

**Comment by maxfischer2781** [comment]
You are definitely correct that the case of LFN + ``user==0`` isn't handled properly. As far as I can tell, ``structs.XrdXrootdMon.fstat.FileOPN`` does handle it well (it just loads a number) but ``streams.XrdXrootdMon.fstat`` does not: it just assumes that if there is a ``user`` then there is a mapping for it which is wrong for ``user==0``.

https://github.com/maxfischer2781/xrootdlib/blob/e32b2f365d1de06e8b54bc13ef73754576334271/xrootdlib/streams/XrdXrootdMon/fstat.py#L31-L39

There should definitely be a separate path here for ``record_struct.user == 0``.

---------

Here's the catch: The spec does not seem to say how ``FileCLS`` works without a User/Path map record either – the code currently assumes that its ``fileid`` always works.

By the looks of it, if ``FileOPN`` carries the LFN one has to create the corresponding map entry from that information and store it with the given ``fileid`` (which is currently ignored). This allows ``FileCLS`` to use the information contained inside ``FileOPN``, since they have the same ``fileid``.

**Comment by sognetic** [comment]
Thank you very much for fleshing out my very terse bug report, I hadn't completely figured out the problem. I think matching `FileOPN` and `FileCLS` via the `fileid` without requiring the user would be the expected behavior, yes.
